version: "3.9"

volumes:
  miniodata:
  mongodata:
  postgresdata:

services:
  # ----------------------------
  # OpenSearch
  # ----------------------------
  opensearch:
    image: opensearchproject/opensearch:2.10.0
    container_name: ecommerce_opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - DISABLE_SECURITY_PLUGIN=true    # <--- this disables the security plugin completely
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep green"]
      interval: 30s
      retries: 5

  

  # ----------------------------
  # MinIO
  # ----------------------------
  minio:
    image: minio/minio:latest
    container_name: ecommerce_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      retries: 5

  # ----------------------------
  # Redis
  # ----------------------------
  redis:
    image: redis:7.2
    container_name: ecommerce_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 5

  # ----------------------------
  # MongoDB
  # ----------------------------
  mongo:
    image: mongo:6.0
    container_name: ecommerce_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 5

  # ----------------------------
  # PostgreSQL
  # ----------------------------
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      retries: 5
